spring.application.name=remote
server.port=8080

# --- MySQL 接続設定 ---
spring.datasource.url=jdbc:mysql://localhost:3306/remote?serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=AdminDef
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## --- JPA/Hibernate 設定 ---
# データベースの接続確認に役立ちます
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ログ設定は任意で残す
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=DEBUG
logging.level.org.hibernate.SQL=DEBUG